stages:
  - build
  - test
  - package
  - deploy
job1:
  stage: build
  script:
    - dotnet build

job2:
  stage: build
  script: 
    - cd User.API.UnitTests
    - dotnet test

job3:
  stage: package
  script:
    - cd User.API
    - docker build -t userapi:test
    - docker login -u testuser -p testpassword https://hub.jessetalk.cn/
    - docker tag userapi:test hub.jessetalk.cn/userapi:test
    - docker push hub.jessetalk.cn/uerapi:test
job4:
  stage: deploy
  script:
    - docker run -d -p 80:80 --link mysql01:db --name userapi hub.jessetalk.cn/userapi.test