FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY *.sln ./
COPY User.API/User.API.csproj User.API/
RUN dotnet restore
COPY . ./
WORKDIR /src/User.API
RUN dotnet publish -c Release -o /app

FROM build AS publish
RUN dotnet publish -x Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT [ "dotnet","User.API.dll" ]