version: '3'

services:
 db:
  image: mysql/mysql-server
  command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
  restart: always
  ports:
   - '3307:3306'
  environment:
   MYSQL_ROOT_PASSWORD: Netkyle
   MYSQL_USER: kyle
   MYSQL_PASSWORD: Netkyle
  volumes: 
   - /home/docker/beta/mysql-init:/docker-entrypoint-initdb.d
 web:
  build: .
  container_name: 'UserApi'
  ports:
   -'80:80'
  depends_on:
   - db
